title: Stephen Pierzchajlo # your name (or website title) here
logo: "/images/stephen_cropped2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MSc. in Neuroscience; interested in data science, machine learning, etc.
  <br><br>
  These are my data science projects. I mostly use R and Python.
  <br><br>
  <a href="https://www.linkedin.com/in/stephen-pierzchajlo-326302176/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

article.page {
    float: left;
    width: 100%;
}

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
     
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
