<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Stephen Pierzchajlo">

<title>Journal Of Neuroscience: Bayesian Reanalysis – stephenpierzchajlo.com</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../images/favicon.ico" rel="icon">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="../../../site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="../../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-md " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">stephenpierzchajlo.com</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../content/about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://x.com/pierzchajlo"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/StephenPierzchajlo"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Journal Of Neuroscience: Bayesian Reanalysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Stephen Pierzchajlo </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="project-overview" class="level1">
<h1>Project Overview</h1>
<p>The data I am analysing comes from a paper I recently published in the Journal Of Neuroscience (https://www.jneurosci.org/content/44/22/e1232232024). The paper involves 3 experiments, of which I am only analysing data from the first. I have chosen this study because I actually wanted to do a Bayesian analysis originally, and wanted to do a random effects model as well. We opted for a Frequentist analysis and a 3-way ANOVA. Here I will perform the same analyses using a Bayesian random-effects model.</p>
<section id="short-introduction" class="level2">
<h2 class="anchored" data-anchor-id="short-introduction">Short Introduction</h2>
<p>People are notoriously bad at identifying odors. Herrick (1993) noted that the olfactory cortex of most species is large, relative to other areas, and it is only in humans that the olfactory epithelium becomes dwarfed by the neocortex. This is likely do to evolution favoring cognitive capabilities, along with senses more important to our lives, like vision. Herrick hypothesized that, because the human olfactory cortex still contains dense interconnectivity with other sensory modalities, that maybe olfaction relies on other senses to help with olfactory identification and localization. Additionally, a recent study found that when people describe different types of sensory stimuli, all but olfaction are described abstractly (i.e.&nbsp;bright). Olfactory stimuli alone Are described as object-based (i.e.&nbsp;lemon).</p>
</section>
<section id="participant-information" class="level2">
<h2 class="anchored" data-anchor-id="participant-information">Participant Information</h2>
<p>After removing some participants for poor performance, this dataset includes 63 participants (40 female; age range: 18-65; mean age: 32 years) total.</p>
</section>
<section id="hypotheses" class="level2">
<h2 class="anchored" data-anchor-id="hypotheses">Hypotheses</h2>
<p>We developed a behavioural task where people listened to a predictive cue, were presented with a target, and then had to determine whether the cue and target matched or did not match. The cue was delivered by a voice, and the target was either visual or olfactory. The cue could also be object-based (i.e.&nbsp;lemon) or category-based (i.e.&nbsp;fruit). The targets consisted of 4 stimuli: lavender, lilac, lemon, pear. These could be presented both visually and in an olfactory manner. We hypothesized that, if olfaction requires information from another sensory modality, that their would be a large disparity in reaction time between matching (congruent) and non-matching (incongruent) cues and targets. We further hypothesized that this disparity would not be seen when the targets were visual. We also hypothesized that, in olfaction, this disparity would be larger when the cues were object-based, rather than category based.</p>
</section>
<section id="predictions" class="level2">
<h2 class="anchored" data-anchor-id="predictions">Predictions</h2>
<p>Their are several predictions that are important for this assignment. First, we predicted much slower responses to olfactory targets. We also predicted participants would be slower at responding when cues and targets did not match. We further predicted that this slowness in responding to cues and targets that were incongruent would be larger when the targets were olfactory. Finally, we predicted that, in olfaction, people would respond more slowly to incongruent cues/targets whe nthe cues were object-based.</p>
</section>
</section>
<section id="set-up-workspace" class="level1">
<h1>Set Up Workspace</h1>
<p>Here I am just initializing my workspace.</p>
<section id="load-global-environment" class="level2">
<h2 class="anchored" data-anchor-id="load-global-environment">Load Global Environment</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load variables that are saved outside R</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"C:/Users/STPI0560/Desktop/Archieve/Stat 2.5/assignment/workspace/assignmentworkspace.RData"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="load-libraries" class="level2">
<h2 class="anchored" data-anchor-id="load-libraries">Load Libraries</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load libraries</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(brms)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(bayesplot)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidybayes) </span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="set-ggplot-theme-and-color-scheme" class="level2">
<h2 class="anchored" data-anchor-id="set-ggplot-theme-and-color-scheme">Set ggplot Theme And Color Scheme</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set ggplot theme</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_minimal</span>())</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># set ggplot colors</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>colors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"#d1e1ec"</span>, <span class="st">"#b3cde0"</span>, <span class="st">"#6497b1"</span>, <span class="st">"#005b96"</span>, <span class="st">"#03396c"</span>, <span class="st">"#011f4b"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="the-data" class="level1">
<h1>The Data</h1>
<section id="example-dataframe" class="level2">
<h2 class="anchored" data-anchor-id="example-dataframe">Example Dataframe</h2>
<p>Below is an example for how one participants’ data might look. These data are fake, but provide an overview for how the data are organized.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fill dataframe with fake values for one participant</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>faketable <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">row =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="st">"..."</span>, <span class="dv">44</span>, <span class="dv">45</span>, <span class="dv">46</span>, <span class="dv">47</span>, <span class="st">"..."</span>, <span class="dv">82</span>, <span class="dv">83</span>, <span class="dv">84</span>, <span class="dv">85</span>, <span class="st">"..."</span>, <span class="dv">127</span>, <span class="dv">128</span>, <span class="dv">129</span>, <span class="dv">130</span>),</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">subject =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span>, <span class="at">times =</span> <span class="dv">4</span>), <span class="st">"..."</span>, <span class="fu">rep</span>(<span class="dv">1</span>, <span class="at">times =</span> <span class="dv">4</span>), <span class="st">"..."</span>, <span class="fu">rep</span>(<span class="dv">1</span>, <span class="at">times =</span> <span class="dv">4</span>), <span class="st">"..."</span>, <span class="fu">rep</span>(<span class="dv">1</span>, <span class="at">times =</span> <span class="dv">4</span>)),</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">modality =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"visual"</span>, <span class="at">times =</span> <span class="dv">4</span>), <span class="st">"..."</span>, <span class="fu">rep</span>(<span class="st">"visual"</span>, <span class="at">times =</span> <span class="dv">4</span>), <span class="st">"..."</span>, <span class="fu">rep</span>(<span class="st">"olfactory"</span>, <span class="at">times =</span> <span class="dv">4</span>), <span class="st">"..."</span>, <span class="fu">rep</span>(<span class="st">"olfactory"</span>, <span class="at">times =</span> <span class="dv">4</span>)),</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">congruency =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"congruent"</span>, <span class="st">"incongruent"</span>), <span class="at">times =</span> <span class="dv">2</span>), <span class="st">"..."</span>,<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"congruent"</span>, <span class="st">"incongruent"</span>), <span class="at">times =</span> <span class="dv">2</span>), <span class="st">"..."</span>, <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"congruent"</span>, <span class="st">"incongruent"</span>), <span class="at">times =</span> <span class="dv">2</span>), <span class="st">"..."</span>,<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"congruent"</span>, <span class="st">"incongruent"</span>), <span class="at">times =</span> <span class="dv">2</span>)),</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">cue_type =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"object"</span>, <span class="at">time =</span> <span class="dv">4</span>), <span class="st">"..."</span>, <span class="fu">rep</span>(<span class="st">"category"</span>, <span class="at">times =</span> <span class="dv">4</span>), <span class="st">"..."</span>, <span class="fu">rep</span>(<span class="st">"object"</span>, <span class="at">time =</span> <span class="dv">4</span>), <span class="st">"..."</span>, <span class="fu">rep</span>(<span class="st">"category"</span>, <span class="at">times =</span> <span class="dv">4</span>)),</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">auditory_cue =</span> <span class="fu">c</span>(<span class="st">"lavender"</span>, <span class="st">"lilac"</span>, <span class="st">"lemon"</span>, <span class="st">"pear"</span>, <span class="st">"..."</span>, <span class="st">"flower"</span>, <span class="st">"flower"</span>, <span class="st">"fruit"</span>, <span class="st">"fruit"</span>, <span class="st">"..."</span>, <span class="st">"lavender"</span>, <span class="st">"lilac"</span>, <span class="st">"lemon"</span>, <span class="st">"pear"</span>, <span class="st">"..."</span>, <span class="st">"flower"</span>, <span class="st">"flower"</span>, <span class="st">"fruit"</span>, <span class="st">"fruit"</span>),</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">target =</span> <span class="fu">c</span>(<span class="st">"lavender"</span>, <span class="st">"lavender"</span>, <span class="st">"lemon"</span>, <span class="st">"lemon"</span>, <span class="st">"..."</span>, <span class="st">"lavender"</span>, <span class="st">"pear"</span>, <span class="st">"lemon"</span>, <span class="st">"lilac"</span>, <span class="st">"..."</span>, <span class="st">"lavender"</span>, <span class="st">"lavender"</span>, <span class="st">"lemon"</span>, <span class="st">"lemon"</span>, <span class="st">"..."</span>, <span class="st">"lavender"</span>, <span class="st">"pear"</span>, <span class="st">"lemon"</span>, <span class="st">"lilac"</span>),</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">reaction_time =</span> <span class="fu">c</span>(<span class="dv">564</span>, <span class="dv">740</span>, <span class="dv">602</span>, <span class="dv">557</span>, <span class="st">"..."</span>, <span class="dv">471</span>, <span class="dv">649</span>, <span class="dv">668</span>, <span class="dv">519</span>, <span class="st">"..."</span>, <span class="dv">1121</span>, <span class="dv">1576</span>, <span class="dv">1844</span>, <span class="dv">1343</span>, <span class="st">"..."</span>, <span class="dv">1876</span>, <span class="dv">1265</span>, <span class="dv">1721</span>, <span class="dv">1846</span>)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="co"># display fake dataframe with nice kable styling</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>faketable <span class="sc">%&gt;%</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">caption =</span> <span class="st">"Example dataframe"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_classic</span>(<span class="at">full_width =</span> F, <span class="at">html_font =</span> <span class="st">"Cambria"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="lightable-classic caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Example dataframe</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">row</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">subject</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">modality</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">congruency</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">cue_type</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">auditory_cue</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">target</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">reaction_time</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">visual</td>
<td style="text-align: left;">congruent</td>
<td style="text-align: left;">object</td>
<td style="text-align: left;">lavender</td>
<td style="text-align: left;">lavender</td>
<td style="text-align: left;">564</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">visual</td>
<td style="text-align: left;">incongruent</td>
<td style="text-align: left;">object</td>
<td style="text-align: left;">lilac</td>
<td style="text-align: left;">lavender</td>
<td style="text-align: left;">740</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">visual</td>
<td style="text-align: left;">congruent</td>
<td style="text-align: left;">object</td>
<td style="text-align: left;">lemon</td>
<td style="text-align: left;">lemon</td>
<td style="text-align: left;">602</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">visual</td>
<td style="text-align: left;">incongruent</td>
<td style="text-align: left;">object</td>
<td style="text-align: left;">pear</td>
<td style="text-align: left;">lemon</td>
<td style="text-align: left;">557</td>
</tr>
<tr class="odd">
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
</tr>
<tr class="even">
<td style="text-align: left;">44</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">visual</td>
<td style="text-align: left;">congruent</td>
<td style="text-align: left;">category</td>
<td style="text-align: left;">flower</td>
<td style="text-align: left;">lavender</td>
<td style="text-align: left;">471</td>
</tr>
<tr class="odd">
<td style="text-align: left;">45</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">visual</td>
<td style="text-align: left;">incongruent</td>
<td style="text-align: left;">category</td>
<td style="text-align: left;">flower</td>
<td style="text-align: left;">pear</td>
<td style="text-align: left;">649</td>
</tr>
<tr class="even">
<td style="text-align: left;">46</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">visual</td>
<td style="text-align: left;">congruent</td>
<td style="text-align: left;">category</td>
<td style="text-align: left;">fruit</td>
<td style="text-align: left;">lemon</td>
<td style="text-align: left;">668</td>
</tr>
<tr class="odd">
<td style="text-align: left;">47</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">visual</td>
<td style="text-align: left;">incongruent</td>
<td style="text-align: left;">category</td>
<td style="text-align: left;">fruit</td>
<td style="text-align: left;">lilac</td>
<td style="text-align: left;">519</td>
</tr>
<tr class="even">
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
</tr>
<tr class="odd">
<td style="text-align: left;">82</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">olfactory</td>
<td style="text-align: left;">congruent</td>
<td style="text-align: left;">object</td>
<td style="text-align: left;">lavender</td>
<td style="text-align: left;">lavender</td>
<td style="text-align: left;">1121</td>
</tr>
<tr class="even">
<td style="text-align: left;">83</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">olfactory</td>
<td style="text-align: left;">incongruent</td>
<td style="text-align: left;">object</td>
<td style="text-align: left;">lilac</td>
<td style="text-align: left;">lavender</td>
<td style="text-align: left;">1576</td>
</tr>
<tr class="odd">
<td style="text-align: left;">84</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">olfactory</td>
<td style="text-align: left;">congruent</td>
<td style="text-align: left;">object</td>
<td style="text-align: left;">lemon</td>
<td style="text-align: left;">lemon</td>
<td style="text-align: left;">1844</td>
</tr>
<tr class="even">
<td style="text-align: left;">85</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">olfactory</td>
<td style="text-align: left;">incongruent</td>
<td style="text-align: left;">object</td>
<td style="text-align: left;">pear</td>
<td style="text-align: left;">lemon</td>
<td style="text-align: left;">1343</td>
</tr>
<tr class="odd">
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
</tr>
<tr class="even">
<td style="text-align: left;">127</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">olfactory</td>
<td style="text-align: left;">congruent</td>
<td style="text-align: left;">category</td>
<td style="text-align: left;">flower</td>
<td style="text-align: left;">lavender</td>
<td style="text-align: left;">1876</td>
</tr>
<tr class="odd">
<td style="text-align: left;">128</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">olfactory</td>
<td style="text-align: left;">incongruent</td>
<td style="text-align: left;">category</td>
<td style="text-align: left;">flower</td>
<td style="text-align: left;">pear</td>
<td style="text-align: left;">1265</td>
</tr>
<tr class="even">
<td style="text-align: left;">129</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">olfactory</td>
<td style="text-align: left;">congruent</td>
<td style="text-align: left;">category</td>
<td style="text-align: left;">fruit</td>
<td style="text-align: left;">lemon</td>
<td style="text-align: left;">1721</td>
</tr>
<tr class="odd">
<td style="text-align: left;">130</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">olfactory</td>
<td style="text-align: left;">incongruent</td>
<td style="text-align: left;">category</td>
<td style="text-align: left;">fruit</td>
<td style="text-align: left;">lilac</td>
<td style="text-align: left;">1846</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
<section id="load-data" class="level2">
<h2 class="anchored" data-anchor-id="load-data">Load Data</h2>
<p>The data I am using is a single .csv file from our previous experiment. These data were pre-processed in a separate R script that took each individual participants’ data and combined them into a single dataframe. The data are not aggregated, so they still represent the participants’ raw data. However, 5 participants were removed for having very low accuracy in the task. Additionally, we were only interested in trials where participants’ correctly determined whether the cue and target matched/did not match. Thus, these data only represent “correct” trials. Additionally, all participants’ in this dataset had at least 80% accuracy across the study.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load data</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> <span class="st">"C:/Users/STPI0560/Desktop/Archieve/Stat 2.5/assignment/data/object_category.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># glimpse first few rows</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  participant modality  congruency cue_type      cue   target reaction_time
1         101   visual incongruent   object     Pear Lavender     1933.3277
2         101   visual   congruent   object     Pear     Pear      400.3761
3         101   visual   congruent   object    Lemon    Lemon      500.3686
4         101   visual incongruent   object    Lilac     Pear      833.7295
5         101   visual   congruent   object    Lilac    Lilac      533.7733
6         101   visual   congruent   object Lavender Lavender      883.7940</code></pre>
</div>
</div>
<p>Some columns need to be changed to factors for the analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Columns to convert to factors</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>cols_to_factor <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"participant"</span>, <span class="st">"modality"</span>, <span class="st">"congruency"</span>, <span class="st">"cue_type"</span>, <span class="st">"cue"</span>, <span class="st">"target"</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert specified columns to factors</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>df[cols_to_factor] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(df[cols_to_factor], as.factor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>First, I wanted to plot the distribution of the dependent variable (reaction time) for both visual and olfactory target trials. This is because reaction time is often skewed. If the distributions are indeed skewed, I may want to model them using an Exgaussian distribution.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add mean lines</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x=</span>reaction_time, <span class="at">fill =</span> modality)) <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">100</span>)<span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"top"</span>) <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(colors[<span class="dv">2</span>], colors[<span class="dv">5</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="1-jneuro-behavioural_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>They definitely appear skewed. Thus, I will take that into account with my model. However, I want to try both an Exgaussian and Gaussian model. I will then see how well each model recovers the distribution of the dependent variable using a Posterior Predictive Check (PPC).</p>
</section>
</section>
<section id="bayesian-hierarchical-model" class="level1">
<h1>Bayesian Hierarchical Model</h1>
<p>This model will be a 3-way factorial design. Originally we did not want to have a 3-way design as we believed we would be underpowered to detect a 3-way interaction. However, a reviewer insisted on adopting this approach. Thus, to match the original study, I will do that here. Here I want to see how target modality (visual, olfactory), cue/target congruency (congruent, incongruent), and cue-type (object-cue, category-cue) affect reaction time. Most importantly, I will look at the 2-way interaction between modality and congruency, and the 3-way interaction between modality, congruency, and cue-type.</p>
<p>I want to add a random intercept and random slopes for each target and each participant in the model. I believe my model should look something like what I have outlined below.</p>
<section id="notations" class="level4">
<h4 class="anchored" data-anchor-id="notations">Notations</h4>
<ul>
<li><span class="math inline">\(Y_{ijk}\)</span> : Reaction time for participant <span class="math inline">\(i\)</span>, condition <span class="math inline">\(j\)</span>, target <span class="math inline">\(k\)</span>.</li>
<li><span class="math inline">\(M_j\)</span>: Modality.</li>
<li><span class="math inline">\(C_j\)</span>: Congruency.</li>
<li><span class="math inline">\(T_j\)</span>: Cue_type.</li>
<li><span class="math inline">\({Target}_k\)</span>: Target.</li>
</ul>
</section>
<section id="parameters" class="level4">
<h4 class="anchored" data-anchor-id="parameters">Parameters</h4>
<ul>
<li><span class="math inline">\(\beta_0\)</span>: Intercept.</li>
<li><span class="math inline">\(\beta_1\)</span>: Coefficient for modality <span class="math inline">\(M\)</span>.</li>
<li><span class="math inline">\(\beta_2\)</span>: Coefficient for congruency <span class="math inline">\(C\)</span>.</li>
<li><span class="math inline">\(\beta_3\)</span>: Coefficient for cue_type <span class="math inline">\(T\)</span>.</li>
<li><span class="math inline">\(\beta_{12}\)</span>: Coefficient for <span class="math inline">\(M \times C\)</span>.</li>
<li><span class="math inline">\(\beta_{13}\)</span>: Coefficient for <span class="math inline">\(M \times T\)</span>.</li>
<li><span class="math inline">\(\beta_{23}\)</span>: Coefficient for <span class="math inline">\(C \times T\)</span>.</li>
<li><span class="math inline">\(\beta_{123}\)</span>: Coefficient for <span class="math inline">\(M \times C \times T\)</span>.</li>
</ul>
</section>
<section id="random-effects" class="level4">
<h4 class="anchored" data-anchor-id="random-effects">Random Effects</h4>
<ul>
<li><span class="math inline">\(u_{0i}\)</span>: Random intercept for participant <span class="math inline">\(i\)</span>.</li>
<li><span class="math inline">\(u_{1i}\)</span>: Random slope for target <span class="math inline">\(k\)</span> by participant <span class="math inline">\(i\)</span>.</li>
</ul>
</section>
<section id="model-equation" class="level4">
<h4 class="anchored" data-anchor-id="model-equation">Model Equation</h4>
<p>The full model equation is:</p>
<p><span class="math inline">\(Y_{ijk} = \beta_0 + \beta_1 M_j + \beta_2 C_j + \beta_3 T_j + \beta_{12} (M_j \cdot C_j) + \beta_{13} (M_j \cdot T_j) + \beta_{23} (C_j \cdot T_j) + \beta_{123} (M_j \cdot C_j \cdot T_j) + u_{0i} + u_{1i} \text{Target}_k + \epsilon_{ijk}\)</span></p>
</section>
<section id="priors" class="level4">
<h4 class="anchored" data-anchor-id="priors">Priors</h4>
<ul>
<li>Coefficients:
<ul>
<li><span class="math inline">\(\beta_0 \sim \mathcal{N}(1200, 200)\)</span></li>
<li><span class="math inline">\(\beta_1 \sim \mathcal{N}(500, 100)\)</span></li>
<li><span class="math inline">\(\beta_2 \sim \mathcal{N}(200, 50)\)</span></li>
<li><span class="math inline">\(\beta_3 \sim \mathcal{N}(100, 50)\)</span></li>
<li><span class="math inline">\(\beta_{12}, \beta_{13}, \beta_{23}, \beta_{123} \sim \mathcal{N}(0, 1)\)</span></li>
</ul></li>
<li>Random effects:
<ul>
<li><span class="math inline">\((u_{0i}, u_{1i})^T \sim \mathcal{N}(0, \Sigma_u)\)</span></li>
<li><span class="math inline">\(Sigma_u\)</span> is the covariance matrix of the random effects, where <span class="math inline">\(\Sigma_u \sim \text{LKJ}(2)\)</span></li>
</ul></li>
</ul>
</section>
<section id="residual-error" class="level4">
<h4 class="anchored" data-anchor-id="residual-error">Residual Error</h4>
<ul>
<li><span class="math inline">\(\epsilon_{ijk} \sim \mathcal{N}(0, \sigma^2)\)</span></li>
</ul>
<p>Where <span class="math inline">\(\text{ExGaussian}(\mu, \sigma, \tau)\)</span> denotes the ex-Gaussian distribution with: - <span class="math inline">\(\mu\)</span>: Mean of the normal component. - <span class="math inline">\(\sigma\)</span>: Standard deviation of the normal component. - <span class="math inline">\(\tau\)</span>: Mean of the exponential component.</p>
<p>Additionally, <span class="math inline">\(\text{Gaussian}(\mu, \sigma)\)</span> denotes the Gaussian distribution with: - <span class="math inline">\(\mu\)</span>: Mean of the normal component. - <span class="math inline">\(\sigma\)</span>: Standard deviation of the normal component.</p>
<p>The ex-Gaussian distribution combines a normal distribution with parameters <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span>, and an exponential distribution with parameter <span class="math inline">\(\tau\)</span>. The Guassian distribution does not include the parameter <span class="math inline">\(\tau\)</span>. I am using both the Gaussian and ex-Gaussian distribution to model reaction time.</p>
</section>
<section id="gaussian-model" class="level2">
<h2 class="anchored" data-anchor-id="gaussian-model">Gaussian model</h2>
<section id="prior-predictive-check." class="level3">
<h3 class="anchored" data-anchor-id="prior-predictive-check.">Prior Predictive Check.</h3>
<p>I want to use informative priors for my model as I have already conducted several other similar studies and have several ideas about how reaction times will differ between different conditions. My original plan was to conduct a Prior Predictive Check to see how my informative priors would generate reaction time data. However, this proved too difficult and time consuming. The Prior Predictive Check gave estimates of some pararmeters in the millions, while also having very low effective sample sizes (ess). Some of the ess values were as low as 20, even with 4 chains running for 10,000 iterations. I think the model is simply to complex for the number of iterations I would need to run for stable estimates. Therefore, I will be going ahead without a Prior Predictive Check.</p>
</section>
<section id="informative-priors" class="level3">
<h3 class="anchored" data-anchor-id="informative-priors">Informative Priors</h3>
<p>I decided to use informative priors as I have run several studies looking at modality and congruency regarding vision and olfaction. Those have been outlined in the Notation section above. I did not put informative priors on the interaction terms however, because it is very hard to predict exactly how they will turn out.</p>
</section>
<section id="fitting-gaussian-model-in-brm" class="level3">
<h3 class="anchored" data-anchor-id="fitting-gaussian-model-in-brm">Fitting Gaussian Model in brm</h3>
<p>First, I estimated the 3-way factorial model using a Gaussian distribution.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># run Gaussian model in brm</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>gaussian_model <span class="ot">&lt;-</span> <span class="fu">brm</span>(</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  reaction_time <span class="sc">~</span> modality<span class="sc">*</span>congruency<span class="sc">*</span>cue_type <span class="sc">+</span> (target<span class="sc">|</span>participant),</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> df,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">gaussian</span>(),</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">prior =</span> <span class="fu">c</span>(<span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">1200</span>, <span class="dv">200</span>), <span class="at">class =</span> Intercept),</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>            <span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">500</span>, <span class="dv">100</span>), <span class="at">class =</span> b, <span class="at">coef =</span> <span class="st">"modalityvisual"</span>),</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>            <span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">200</span>, <span class="dv">50</span>), <span class="at">class =</span> b, <span class="at">coef =</span> <span class="st">"congruencyincongruent"</span>),</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>            <span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">100</span>, <span class="dv">50</span>), <span class="at">class =</span> b, <span class="at">coef =</span> <span class="st">"cue_typeobject"</span>),</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>            <span class="fu">prior</span>(<span class="fu">cauchy</span>(<span class="dv">0</span>, <span class="dv">2</span>), <span class="at">class =</span> sd),</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>            <span class="fu">prior</span>(<span class="fu">cauchy</span>(<span class="dv">0</span>, <span class="dv">2</span>), <span class="at">class =</span> sigma),</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>            <span class="fu">prior</span>(<span class="fu">lkj</span>(<span class="dv">2</span>), <span class="at">class =</span> cor)),</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">iter  =</span> <span class="dv">6000</span>,</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">warmup =</span> <span class="dv">2000</span>,</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">file =</span> <span class="st">"C:/Users/STPI0560/Desktop/Archieve/Stat 2.5/assignment/models/gaussian_model"</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="exgaussian-model" class="level2">
<h2 class="anchored" data-anchor-id="exgaussian-model">Exgaussian Model</h2>
<p>Next, I run an Exgaussian model. Everything is identical to the Gaussian model otherwise.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># run Exgaussian model in brm</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>exgaussian_model <span class="ot">&lt;-</span> <span class="fu">brm</span>(</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  reaction_time <span class="sc">~</span> modality<span class="sc">*</span>congruency<span class="sc">*</span>cue_type <span class="sc">+</span> (target<span class="sc">|</span>participant),</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> df,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">exgaussian</span>(),</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">prior =</span> <span class="fu">c</span>(<span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">1200</span>, <span class="dv">200</span>), <span class="at">class =</span> Intercept),</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>            <span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">500</span>, <span class="dv">100</span>), <span class="at">class =</span> b, <span class="at">coef =</span> <span class="st">"modalityvisual"</span>),</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>            <span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">200</span>, <span class="dv">50</span>), <span class="at">class =</span> b, <span class="at">coef =</span> <span class="st">"congruencyincongruent"</span>),</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>            <span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">100</span>, <span class="dv">50</span>), <span class="at">class =</span> b, <span class="at">coef =</span> <span class="st">"cue_typeobject"</span>),</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>            <span class="fu">prior</span>(<span class="fu">cauchy</span>(<span class="dv">0</span>, <span class="dv">2</span>), <span class="at">class =</span> sd),</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>            <span class="fu">prior</span>(<span class="fu">cauchy</span>(<span class="dv">0</span>, <span class="dv">2</span>), <span class="at">class =</span> sigma),</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>            <span class="fu">prior</span>(<span class="fu">lkj</span>(<span class="dv">2</span>), <span class="at">class =</span> cor)),</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">iter  =</span> <span class="dv">6000</span>,</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">warmup =</span> <span class="dv">2000</span>, </span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">file =</span> <span class="st">"C:/Users/STPI0560/Desktop/Archieve/Stat 2.5/assignment/models/exgaussian_model"</span>,</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Using informative priors with the Exgaussian model led to sever errors, with R-hat values over 3 and ess values as low as 5. Not shown here, I ran another Exgaussian model where I used the default priors brm gives you. This model did well, so I will use it from here.</p>
</section>
<section id="model-comparison" class="level2">
<h2 class="anchored" data-anchor-id="model-comparison">Model Comparison</h2>
<p>My plan was to first compare these models using the loo function. However, due to their complexity, I would need to redo both models and save the parameters as the models go. I have done this before and know it would take at least twice as long to run (sometimes longer). Given that the Exgaussian model took more than a day to complete, I just don’t have time. Instead I will let the PPC below guide my model selection.</p>
</section>
</section>
<section id="posterior-predictive-checks" class="level1">
<h1>Posterior Predictive Checks</h1>
<p>Now that I have the two models, I want to see how each one recovers the dependent variable. I will perform a PPC on both models to see.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get reaction time distribution</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> df<span class="sc">$</span>reaction_time</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Draw 500 reaction time distributions from Gaussian model</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>yrep <span class="ot">&lt;-</span> <span class="fu">posterior_predict</span>(gaussian_model, <span class="at">draws =</span> <span class="dv">500</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Draw 500 reaction time distributions from Exgaussian model</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>yrep_exgaus <span class="ot">&lt;-</span> <span class="fu">posterior_predict</span>(exgaussian_model, <span class="at">draws =</span> <span class="dv">500</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set color scheme</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">color_scheme_set</span>(<span class="st">"brightblue"</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co"># gaussian ppc graph</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>gaussian_ppc <span class="ot">&lt;-</span> <span class="fu">ppc_dens_overlay</span>(y, yrep[<span class="dv">1</span><span class="sc">:</span><span class="dv">50</span>, ]) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Gaussian PPC"</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># exgaussian ppc graph</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>exgaussian_ppc <span class="ot">&lt;-</span> <span class="fu">ppc_dens_overlay</span>(y, yrep_exgaus[<span class="dv">1</span><span class="sc">:</span><span class="dv">50</span>, ]) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Exgaussian PPC"</span>)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Arrange the plots side by side</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(gaussian_ppc, exgaussian_ppc, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="1-jneuro-behavioural_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="2400"></p>
</figure>
</div>
</div>
</div>
<p>Neither model recovers the dependent variable perfectly, perhaps due to its bimodal nature. I would actually say that the Guassian performs slightly better here as it undershoots the first large bump (visual target peak responses), but almost matches the second smaller bump. The Exgaussian model overshoots the first bump, and then undershoots the second. I could standardize the predictors which might help with this fit. However, I do not actually like interpreting standardized coefficients since their are additional mental steps you need to take to understand the output. I would prefer to work with the unstandardized predictors, even if the PPC is not perfect.</p>
<p>I can also see how well the ppc recovers the mean reaction time split by different groups. I decided to check how well each model can represent the two means for modality, congruency, and cue-type.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># make 6 graphs, 3 for Guassian and 3 for Exgaussian</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>gaussian_modality_ppc <span class="ot">&lt;-</span> <span class="fu">ppc_stat_grouped</span>(y, yrep[<span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>, ], <span class="at">group =</span> df<span class="sc">$</span>modality, <span class="at">stat =</span> <span class="st">"mean"</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Gaussian PPC"</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>exgaussian_modality_ppc <span class="ot">&lt;-</span> <span class="fu">ppc_stat_grouped</span>(y, yrep_exgaus[<span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>, ], <span class="at">group =</span> df<span class="sc">$</span>modality, <span class="at">stat =</span> <span class="st">"mean"</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Exgaussian PPC"</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>gaussian_congruency_ppc <span class="ot">&lt;-</span> <span class="fu">ppc_stat_grouped</span>(y, yrep[<span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>, ], <span class="at">group =</span> df<span class="sc">$</span>congruency, <span class="at">stat =</span> <span class="st">"mean"</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Gaussian PPC"</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>exgaussian_congruency_ppc <span class="ot">&lt;-</span> <span class="fu">ppc_stat_grouped</span>(y, yrep_exgaus[<span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>, ], <span class="at">group =</span> df<span class="sc">$</span>congruency, <span class="at">stat =</span> <span class="st">"mean"</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Exgaussian PPC"</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>gaussian_cuetype_ppc <span class="ot">&lt;-</span> <span class="fu">ppc_stat_grouped</span>(y, yrep[<span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>, ], <span class="at">group =</span> df<span class="sc">$</span>cue_type, <span class="at">stat =</span> <span class="st">"mean"</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Gaussian PPC"</span>)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>exgaussian_cuetype_ppc <span class="ot">&lt;-</span> <span class="fu">ppc_stat_grouped</span>(y, yrep_exgaus[<span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>, ], <span class="at">group =</span> df<span class="sc">$</span>cue_type, <span class="at">stat =</span> <span class="st">"mean"</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Exgaussian PPC"</span>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the 6 graphs in a 3 x 2 grid</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(gaussian_modality_ppc, exgaussian_modality_ppc,</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>             gaussian_congruency_ppc, exgaussian_congruency_ppc,</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>             gaussian_cuetype_ppc, exgaussian_cuetype_ppc,</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>             <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">nrow =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="1-jneuro-behavioural_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="3000"></p>
</figure>
</div>
</div>
</div>
<p>It’s pretty clear that the Exgaussian model does not recover the dependent variable very well. Thus, I will continue the analysis using the Guassian model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># remove ppc variables (they take up a lot of space)</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(y)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(yrep)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(yrep_exgaus)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="gaussian-model-diagnostics-check" class="level1">
<h1>Gaussian Model Diagnostics check</h1>
<section id="mcmc-traceplots" class="level2">
<h2 class="anchored" data-anchor-id="mcmc-traceplots">MCMC Traceplots</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mcmc_trace</span>(gaussian_model, <span class="at">pars =</span> <span class="fu">c</span>(<span class="st">"b_Intercept"</span>, <span class="st">"b_modalityvisual"</span>, <span class="st">"b_congruencyincongruent"</span>, <span class="st">"b_cue_typeobject"</span>, <span class="st">"b_modalityvisual:congruencyincongruent"</span>, <span class="st">"b_modalityvisual:cue_typeobject"</span>, <span class="st">"b_congruencyincongruent:cue_typeobject"</span>, <span class="st">"b_modalityvisual:congruencyincongruent:cue_typeobject"</span>, <span class="st">"sigma"</span>), </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">facet_args =</span> <span class="fu">list</span>(<span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">strip.position =</span> <span class="st">"left"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="1-jneuro-behavioural_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="2700"></p>
</figure>
</div>
</div>
</div>
<p>All chains had Rhat values of 1, so I know they converged. This just gives a bit more visual evidence of that.</p>
</section>
</section>
<section id="gaussian-model-fixed-effect-estimates" class="level1">
<h1>Gaussian Model Fixed Effect Estimates</h1>
<p>Before looking at outputs, I want to discuss the model summary.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># select fixed-effects</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>gaussian_summary <span class="ot">&lt;-</span> <span class="fu">fixef</span>(gaussian_model)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="co"># display fake dataframe with nice kable styling</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>gaussian_summary <span class="sc">%&gt;%</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">caption =</span> <span class="st">"Fixed-effect summary"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_classic</span>(<span class="at">full_width =</span> F, <span class="at">html_font =</span> <span class="st">"Cambria"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="lightable-classic caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Fixed-effect summary</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Est.Error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q2.5</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q97.5</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: right;">1763.80622</td>
<td style="text-align: right;">40.74753</td>
<td style="text-align: right;">1682.65982</td>
<td style="text-align: right;">1844.08140</td>
</tr>
<tr class="even">
<td style="text-align: left;">modalityvisual</td>
<td style="text-align: right;">-1176.19344</td>
<td style="text-align: right;">13.88879</td>
<td style="text-align: right;">-1203.60028</td>
<td style="text-align: right;">-1149.00212</td>
</tr>
<tr class="odd">
<td style="text-align: left;">congruencyincongruent</td>
<td style="text-align: right;">109.16309</td>
<td style="text-align: right;">13.97318</td>
<td style="text-align: right;">81.54296</td>
<td style="text-align: right;">136.55348</td>
</tr>
<tr class="even">
<td style="text-align: left;">cue_typeobject</td>
<td style="text-align: right;">-118.04836</td>
<td style="text-align: right;">13.74276</td>
<td style="text-align: right;">-144.70101</td>
<td style="text-align: right;">-90.69817</td>
</tr>
<tr class="odd">
<td style="text-align: left;">modalityvisual:congruencyincongruent</td>
<td style="text-align: right;">-53.85335</td>
<td style="text-align: right;">19.57608</td>
<td style="text-align: right;">-92.02107</td>
<td style="text-align: right;">-15.15032</td>
</tr>
<tr class="even">
<td style="text-align: left;">modalityvisual:cue_typeobject</td>
<td style="text-align: right;">67.15566</td>
<td style="text-align: right;">19.52747</td>
<td style="text-align: right;">28.77962</td>
<td style="text-align: right;">105.27742</td>
</tr>
<tr class="odd">
<td style="text-align: left;">congruencyincongruent:cue_typeobject</td>
<td style="text-align: right;">-4.88533</td>
<td style="text-align: right;">19.87079</td>
<td style="text-align: right;">-43.57404</td>
<td style="text-align: right;">33.98897</td>
</tr>
<tr class="even">
<td style="text-align: left;">modalityvisual:congruencyincongruent:cue_typeobject</td>
<td style="text-align: right;">15.12504</td>
<td style="text-align: right;">27.86762</td>
<td style="text-align: right;">-38.99643</td>
<td style="text-align: right;">69.25071</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>First, participants were 1176ms faster at responding to visual targets than they are olfactory targets. Participants are 109ms slower at responding to targets that do not match (incongruent) the cue compared to targets that do match (congruent) the cue. Participants are 118ms faster at responding to targets when an object-based cue precedes it compared to when a category cue precedes it. Participants are 54ms slower at responding to incongruent cue/target presentations, but only when the target is olfactory. The other effects overlap quite substantially with zero, so I will not go into detail regarding those. Additionally, all Rhat values were 1, and the effective sample sizes were very large. Below I display the full summary.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gaussian_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Family: gaussian 
  Links: mu = identity; sigma = identity 
Formula: reaction_time ~ modality * congruency * cue_type + (target | participant) 
   Data: df (Number of observations: 11476) 
  Draws: 4 chains, each with iter = 6000; warmup = 2000; thin = 1;
         total post-warmup draws = 16000

Multilevel Hyperparameters:
~participant (Number of levels: 64) 
                             Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS
sd(Intercept)                  258.65     24.50   216.31   311.55 1.00     2907
sd(targetLemon)                 81.51     14.36    54.02   110.53 1.00     2563
sd(targetLilac)                103.74     14.65    76.74   133.59 1.00     2361
sd(targetPear)                  51.47     29.29     0.37    94.40 1.00      455
cor(Intercept,targetLemon)      -0.15      0.17    -0.46     0.20 1.00     2577
cor(Intercept,targetLilac)      -0.06      0.17    -0.37     0.27 1.00     1796
cor(targetLemon,targetLilac)     0.77      0.11     0.51     0.93 1.00     3562
cor(Intercept,targetPear)       -0.15      0.24    -0.56     0.45 1.00     6762
cor(targetLemon,targetPear)      0.32      0.29    -0.44     0.73 1.00     1442
cor(targetLilac,targetPear)      0.31      0.28    -0.44     0.71 1.00     1679
                             Tail_ESS
sd(Intercept)                    5437
sd(targetLemon)                  6648
sd(targetLilac)                  8877
sd(targetPear)                   1565
cor(Intercept,targetLemon)       7532
cor(Intercept,targetLilac)       6575
cor(targetLemon,targetLilac)     7012
cor(Intercept,targetPear)        2309
cor(targetLemon,targetPear)      1839
cor(targetLilac,targetPear)      1696

Regression Coefficients:
                                                    Estimate Est.Error l-95% CI
Intercept                                            1763.81     40.75  1682.66
modalityvisual                                      -1176.19     13.89 -1203.60
congruencyincongruent                                 109.16     13.97    81.54
cue_typeobject                                       -118.05     13.74  -144.70
modalityvisual:congruencyincongruent                  -53.85     19.58   -92.02
modalityvisual:cue_typeobject                          67.16     19.53    28.78
congruencyincongruent:cue_typeobject                   -4.89     19.87   -43.57
modalityvisual:congruencyincongruent:cue_typeobject    15.13     27.87   -39.00
                                                    u-95% CI Rhat Bulk_ESS
Intercept                                            1844.08 1.00      847
modalityvisual                                      -1149.00 1.00    11091
congruencyincongruent                                 136.55 1.00    11029
cue_typeobject                                        -90.70 1.00    11197
modalityvisual:congruencyincongruent                  -15.15 1.00    10397
modalityvisual:cue_typeobject                         105.28 1.00     9408
congruencyincongruent:cue_typeobject                   33.99 1.00    10806
modalityvisual:congruencyincongruent:cue_typeobject    69.25 1.00     9653
                                                    Tail_ESS
Intercept                                               2107
modalityvisual                                         12780
congruencyincongruent                                  12235
cue_typeobject                                         13101
modalityvisual:congruencyincongruent                   12388
modalityvisual:cue_typeobject                          12467
congruencyincongruent:cue_typeobject                   12816
modalityvisual:congruencyincongruent:cue_typeobject    12229

Further Distributional Parameters:
      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sigma   385.21      2.66   380.06   390.50 1.00    15627    11084

Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
and Tail_ESS are effective sample size measures, and Rhat is the potential
scale reduction factor on split chains (at convergence, Rhat = 1).</code></pre>
</div>
</div>
<p>Next I am calculating all possible estimated reaction times from the model depending on modality, congruency, and cue type. I am not going into detail below about why certain reaction time estimates are the result of specific combinations of coefficients. Hopefully it will be obvious based on whether each categorical predictor represents 0 or 1.</p>
<p>olfactory congruent category = <span class="math inline">\(\beta_{0}\)</span> = 1763.81</p>
<p>visual congruent category = <span class="math inline">\(\beta_{0} + \beta_{1}x_{i1}\)</span> = 1763.81 + (-1176.19) = 587.62</p>
<p>olfactory incongruent category = <span class="math inline">\(\beta_{0} + \beta_{2}x_{i2}\)</span> = 1763.81 + 109.16 = 1872.97</p>
<p>visual incongruent category = <span class="math inline">\(\beta_{0} + \beta_{1}x_{i1} + \beta_{2}x_{i2} + \beta_{4}x_{i1}x_{i2}\)</span> = 1763.81 + (-1176.19) + 109.16 + (-53.85) = 642.93</p>
<p>olfactory congruent object = <span class="math inline">\(\beta_{0} + \beta_{3}x_{i3}\)</span> = 1763.81 + (-118.05) = 1645.76</p>
<p>visual congruent object = <span class="math inline">\(\beta_{0} + \beta_{1}x_{i1} + \beta_{3}x_{i3} + \beta_{5}x_{i1}x_{i3}\)</span> = 1763.81 + (-1176.19) + (-118.05) + 67.16 = 536.73</p>
<p>olfactory incongruent object = <span class="math inline">\(\beta_{0} + \beta_{2}x_{i2} + \beta_{3}x_{i3} + \beta_{6}x_{i2}x_{i3}\)</span> = 1763.81 + 109.16 + (-118.05) + -4.89 = 1750.03</p>
<p>visual incongruent object = <span class="math inline">\(\beta_{0} + \beta_{1}x_{i1} + \beta_{2}x_{i2} + \beta_{3}x_{i3} + \beta_{4}x_{i1}x_{i2} + \beta_{5}x_{i1}x_{i3} + \beta_{6}x_{i2}x_{i3} + \beta_{7}x_{i1}x_{i2}x_{i3}\)</span> = 1763.81 + (-1176.19) + 109.16 + (-118.05) + (-53.85) + 67.16 + -4.89 + 15.13 = 602.28</p>
<p>Now that I have my reaction time estimates, I will make a dataframe and then plot it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># make coefficients dataframe</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>coefficient_dataframe <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"modality"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"olfactory"</span>, <span class="st">"olfactory"</span>, <span class="st">"olfactory"</span>, <span class="st">"olfactory"</span>, <span class="st">"visual"</span>, <span class="st">"visual"</span>, <span class="st">"visual"</span>, <span class="st">"visual"</span>),</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"congruency"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"congruent"</span>, <span class="st">"congruent"</span>, <span class="st">"incongruent"</span>, <span class="st">"incongruent"</span>, <span class="st">"congruent"</span>, <span class="st">"congruent"</span>, <span class="st">"incongruent"</span>, <span class="st">"incongruent"</span>),</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"cue_type"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"category"</span>, <span class="st">"object"</span>, <span class="st">"category"</span>, <span class="st">"object"</span>, <span class="st">"category"</span>, <span class="st">"object"</span>, <span class="st">"category"</span>, <span class="st">"object"</span>),</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"reaction_time"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="fl">1763.81</span>, <span class="fl">1645.76</span>, <span class="fl">1872.97</span>, <span class="fl">1750.03</span>, <span class="fl">587.62</span>, <span class="fl">536.73</span>, <span class="fl">642.93</span>, <span class="fl">602.28</span>)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Below I am plotting the estimated fixed effect coefficients.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot coefficients</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(coefficient_dataframe, <span class="fu">aes</span>(<span class="at">x =</span> modality, <span class="at">y =</span> reaction_time, <span class="at">fill =</span> congruency, <span class="at">group =</span> congruency, <span class="at">color =</span> congruency)) <span class="sc">+</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>cue_type) <span class="sc">+</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(colors[<span class="dv">2</span>], colors[<span class="dv">4</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="1-jneuro-behavioural_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Olfactory trials are clearly much slower than visual trials. When the cue and target match (are congruent), people are also faster at responding. The main effect of cue-type is a bit harder to see, but it is apparant that people are faster at responding when cues are object-based. The two-way interaction between modality and congruency is also visible: The disparity between congruent and incongruent responses is larger when the target is olfactory (relative to visual).</p>
<p>One thing to not is that this graph might be a bit misleading. Visually, because there is such a large difference between visual and olfactory reaction times (about 1200ms), it is hard to see smaller effects. Additionally, this is a within-subjects design. Therefore, what matters is individual differences between factors, and this can be hard to see too. I will try to plot things out and explain them in a more intuitive way below.</p>
</section>
<section id="plot-posterior-estimates" class="level1">
<h1>Plot Posterior Estimates</h1>
<section id="fixed-effects" class="level2">
<h2 class="anchored" data-anchor-id="fixed-effects">Fixed Effects</h2>
<p>Here I am taking all draws from all markov chains for all parameters and plotting a histogram of them. I will also take the model estimates and credible intervals and plot those under the histogram.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># make posterior draws dataframe</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>draws_posterior <span class="ot">&lt;-</span> gaussian_model <span class="sc">|&gt;</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># select coefficients</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">spread_draws</span>(b_Intercept, b_modalityvisual, b_congruencyincongruent, b_cue_typeobject, <span class="st">`</span><span class="at">b_modalityvisual:congruencyincongruent</span><span class="st">`</span>, <span class="st">`</span><span class="at">b_modalityvisual:congruencyincongruent:cue_typeobject</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># new column called "posterior"</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">distribution =</span> <span class="st">"posterior"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="main-effects" class="level3">
<h3 class="anchored" data-anchor-id="main-effects">Main Effects</h3>
<p>Below I plot the posterior distributions for the main fixed effects.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># graph of modality</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>modality_main_graph <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(draws_posterior, <span class="fu">aes</span>(<span class="at">x =</span> b_modalityvisual)) <span class="sc">+</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.75</span>, <span class="at">position =</span> <span class="st">"identity"</span>, <span class="at">color =</span> colors[<span class="dv">3</span>], <span class="at">fill =</span> colors[<span class="dv">3</span>]) <span class="sc">+</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fixef</span>(gaussian_model)[<span class="dv">2</span>, <span class="dv">1</span>], <span class="at">y =</span> <span class="dv">0</span>), <span class="at">colour =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fixef</span>(gaussian_model)[<span class="dv">2</span>, <span class="dv">3</span>], <span class="at">y =</span> <span class="dv">0</span>, <span class="at">xend =</span> <span class="fu">fixef</span>(gaussian_model)[<span class="dv">2</span>, <span class="dv">4</span>], <span class="at">yend =</span> <span class="dv">0</span>), <span class="at">size =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Main Effect: Modality"</span>) <span class="sc">+</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Vision - Olfaction"</span>,<span class="at">y =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">9</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>))</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="co"># graph of congruency</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>congruency_main_graph <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(draws_posterior, <span class="fu">aes</span>(<span class="at">x =</span> b_congruencyincongruent)) <span class="sc">+</span></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.75</span>, <span class="at">position =</span> <span class="st">"identity"</span>, <span class="at">color =</span> colors[<span class="dv">3</span>], <span class="at">fill =</span> colors[<span class="dv">3</span>]) <span class="sc">+</span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fixef</span>(gaussian_model)[<span class="dv">3</span>, <span class="dv">1</span>], <span class="at">y =</span> <span class="dv">0</span>), <span class="at">colour =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fixef</span>(gaussian_model)[<span class="dv">3</span>, <span class="dv">3</span>], <span class="at">y =</span> <span class="dv">0</span>, <span class="at">xend =</span> <span class="fu">fixef</span>(gaussian_model)[<span class="dv">3</span>, <span class="dv">4</span>], <span class="at">yend =</span> <span class="dv">0</span>), <span class="at">size =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Main Effect: Congruency"</span>) <span class="sc">+</span></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Incongruent - Congruent"</span>,<span class="at">y =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">9</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>))</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a><span class="co"># graph of cue-type</span></span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>cuetype_main_graph <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(draws_posterior, <span class="fu">aes</span>(<span class="at">x =</span> b_cue_typeobject)) <span class="sc">+</span></span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.75</span>, <span class="at">position =</span> <span class="st">"identity"</span>, <span class="at">color =</span> colors[<span class="dv">3</span>], <span class="at">fill =</span> colors[<span class="dv">3</span>]) <span class="sc">+</span></span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fixef</span>(gaussian_model)[<span class="dv">4</span>, <span class="dv">1</span>], <span class="at">y =</span> <span class="dv">0</span>), <span class="at">colour =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fixef</span>(gaussian_model)[<span class="dv">4</span>, <span class="dv">3</span>], <span class="at">y =</span> <span class="dv">0</span>, <span class="at">xend =</span> <span class="fu">fixef</span>(gaussian_model)[<span class="dv">4</span>, <span class="dv">4</span>], <span class="at">yend =</span> <span class="dv">0</span>), <span class="at">size =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Main Effect: Cue Type"</span>) <span class="sc">+</span></span>
<span id="cb22-27"><a href="#cb22-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Object-Cue - Category-Cue"</span>,<span class="at">y =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb22-28"><a href="#cb22-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">9</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb22-29"><a href="#cb22-29" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>))</span>
<span id="cb22-30"><a href="#cb22-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-31"><a href="#cb22-31" aria-hidden="true" tabindex="-1"></a><span class="co"># arrange graphs beside one another</span></span>
<span id="cb22-32"><a href="#cb22-32" aria-hidden="true" tabindex="-1"></a><span class="fu">ggarrange</span>(modality_main_graph, congruency_main_graph, cuetype_main_graph, <span class="at">ncol =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="1-jneuro-behavioural_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="3000"></p>
</figure>
</div>
</div>
</div>
<p>First, visual trials are 1176ms faster than olfactory trials. Because olfactory trials are the intercept (1764ms), visual trials are estimated to be approximately 588ms. This is a very big difference, but not surprising as it takes longer to process an odor compared to a visual stimulus. Next, incongruent trials are 109ms slower than congruent trials. So people tend to respond more slowly when the auditory cue and target do not match. Finally, people are 118ms faster at responding to targets when the cue is object-based rather than category-based.</p>
<p>Central to our main hypothesis, we were interested in whether the congruency effect (people responding slower when the cue and target did not match) was larger for olfactory target trials compared to visual target trials.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># graph of modality x congruency posterior</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>congruency_modality_graph <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(draws_posterior, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">b_modalityvisual:congruencyincongruent</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.75</span>, <span class="at">position =</span> <span class="st">"identity"</span>, <span class="at">color =</span> colors[<span class="dv">3</span>], <span class="at">fill =</span> colors[<span class="dv">3</span>]) <span class="sc">+</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fixef</span>(gaussian_model)[<span class="dv">5</span>, <span class="dv">1</span>], <span class="at">y =</span> <span class="dv">0</span>), <span class="at">colour =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fixef</span>(gaussian_model)[<span class="dv">5</span>, <span class="dv">3</span>], <span class="at">y =</span> <span class="dv">0</span>, <span class="at">xend =</span> <span class="fu">fixef</span>(gaussian_model)[<span class="dv">5</span>, <span class="dv">4</span>], <span class="at">yend =</span> <span class="dv">0</span>), <span class="at">size =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Interaction: Modality x Congruency"</span>) <span class="sc">+</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">9</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>))</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>congruency_modality_cuetype_graph <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(draws_posterior, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">b_modalityvisual:congruencyincongruent:cue_typeobject</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.75</span>, <span class="at">position =</span> <span class="st">"identity"</span>, <span class="at">color =</span> colors[<span class="dv">3</span>], <span class="at">fill =</span> colors[<span class="dv">3</span>]) <span class="sc">+</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fixef</span>(gaussian_model)[<span class="dv">8</span>, <span class="dv">1</span>], <span class="at">y =</span> <span class="dv">0</span>), <span class="at">colour =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fixef</span>(gaussian_model)[<span class="dv">8</span>, <span class="dv">3</span>], <span class="at">y =</span> <span class="dv">0</span>, <span class="at">xend =</span> <span class="fu">fixef</span>(gaussian_model)[<span class="dv">8</span>, <span class="dv">4</span>], <span class="at">yend =</span> <span class="dv">0</span>), <span class="at">size =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Interaction: Modality x Congruency x Cue-Type"</span>) <span class="sc">+</span></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">9</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>))</span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a><span class="co"># arrange graphs beside one another</span></span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a><span class="fu">ggarrange</span>(congruency_modality_graph, congruency_modality_cuetype_graph, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="1-jneuro-behavioural_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>This can be interpreted like this: people respond more slowly to incongruent cue target presentations, but this difference is greater when the target is olfactory compared to when it is visual. We could also say they are 53ms slower at responding to incongruent olfactory targets compared to incongruent visual targets. In addition, the 95% credible intervals do not overlap with zero (-92.02, -15.15). All of the 95% most probable reaction times for this interaction are negative, so I think we can say this difference is likely negative too. For comparison, this interaction was statistically significant in the original paper (p = 0.02). I actually think a p-value that close to the threshold is not amazingly convincing, so it kind of matches the interpretation of the credible interval here. The plot on the right represents the 3-way interaction. This lets us see whether the disparity in congruent and incongruent reaction times, which is larger in olfaction, occurs when object-cues preceed the olfactory target. The model suggests this is not the case.</p>
<p>There are other interactions as well, but they were not central to our main hypotheses so I won’t go into them here. In addition, I’m not a fan of 3-way interactions as they are hard to interpret and usually very underpowered to detect, so I don’t see much value in looking at the 3-way interaction here.</p>
</section>
</section>
</section>
<section id="participant-level-predictions" class="level1">
<h1>Participant-Level Predictions</h1>
<p>Because this is a class on random-effect models, I want to look at the random-effects specifically. Below I will process the data and estimates in such a way that I can display the participant-level random-effects and fixed-effects together. I am only doing this as an exercise, so I will just plot the results for the main effect of modality.</p>
<section id="modality-random-effects" class="level2">
<h2 class="anchored" data-anchor-id="modality-random-effects">Modality random effects</h2>
<p>Below is some pre-processing for displaying main random-effects estimates.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># temporary dataframe to be filled in loop</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>temp_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="st">"participant"</span> <span class="ot">=</span> <span class="fu">factor</span>(),</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"empirical_olfactory_rt"</span> <span class="ot">=</span> <span class="fu">numeric</span>(),</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"estimated_olfactory_rt"</span> <span class="ot">=</span> <span class="fu">numeric</span>(),</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"empicial_visual_rt"</span> <span class="ot">=</span> <span class="fu">numeric</span>(),</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"estimated_visual_rt"</span> <span class="ot">=</span> <span class="fu">numeric</span>())</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co"># for each unique participant:</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">unique</span>(df<span class="sc">$</span>participant)) { </span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># ith participants' reaction time random effect for olfaction</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  olfaction_rt_i <span class="ot">&lt;-</span> <span class="fu">fixef</span>(gaussian_model)[<span class="dv">1</span>]  <span class="sc">+</span> <span class="fu">ranef</span>(gaussian_model)<span class="sc">$</span>participant[i, <span class="dv">1</span>, <span class="dv">1</span>] <span class="sc">+</span> <span class="fu">ranef</span>(gaussian_model)<span class="sc">$</span>participant[i, <span class="dv">1</span>, <span class="dv">2</span>] <span class="sc">+</span> <span class="fu">ranef</span>(gaussian_model)<span class="sc">$</span>participant[i, <span class="dv">1</span>, <span class="dv">3</span>] <span class="sc">+</span> <span class="fu">ranef</span>(gaussian_model)<span class="sc">$</span>participant[i, <span class="dv">1</span>, <span class="dv">4</span>]</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># ith participants' reaction time random effect for vision</span></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>  visual_rt_i <span class="ot">&lt;-</span> <span class="fu">fixef</span>(gaussian_model)[<span class="dv">1</span>] <span class="sc">+</span> (<span class="fu">fixef</span>(gaussian_model)[<span class="dv">2</span>]) <span class="sc">+</span> <span class="fu">ranef</span>(gaussian_model)<span class="sc">$</span>participant[i, <span class="dv">1</span>, <span class="dv">1</span>] <span class="sc">+</span> <span class="fu">ranef</span>(gaussian_model)<span class="sc">$</span>participant[i, <span class="dv">1</span>, <span class="dv">2</span>] <span class="sc">+</span> <span class="fu">ranef</span>(gaussian_model)<span class="sc">$</span>participant[i, <span class="dv">1</span>, <span class="dv">3</span>] <span class="sc">+</span> <span class="fu">ranef</span>(gaussian_model)<span class="sc">$</span>participant[i, <span class="dv">1</span>, <span class="dv">4</span>]</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># dataframe of fixed and random modality effect estimates for ith person</span></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>  participant_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="st">"participant"</span> <span class="ot">=</span> i,</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"empirical_olfactory_rt"</span> <span class="ot">=</span> <span class="fu">fixef</span>(gaussian_model)[<span class="dv">1</span>],</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"estimated_olfactory_rt"</span> <span class="ot">=</span> olfaction_rt_i,</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"empicial_visual_rt"</span> <span class="ot">=</span> <span class="fu">fixef</span>(gaussian_model)[<span class="dv">1</span>] <span class="sc">+</span> (<span class="fu">fixef</span>(gaussian_model)[<span class="dv">2</span>]),</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"estimated_visual_rt"</span> <span class="ot">=</span> <span class="fu">fixef</span>(gaussian_model)[<span class="dv">1</span>] <span class="sc">+</span> (<span class="fu">fixef</span>(gaussian_model)[<span class="dv">2</span>]) <span class="sc">+</span> <span class="fu">ranef</span>(gaussian_model)<span class="sc">$</span>participant[i, <span class="dv">1</span>, <span class="dv">1</span>] <span class="sc">+</span> <span class="fu">ranef</span>(gaussian_model)<span class="sc">$</span>participant[i, <span class="dv">1</span>, <span class="dv">2</span>] <span class="sc">+</span> <span class="fu">ranef</span>(gaussian_model)<span class="sc">$</span>participant[i, <span class="dv">1</span>, <span class="dv">3</span>] <span class="sc">+</span> <span class="fu">ranef</span>(gaussian_model)<span class="sc">$</span>participant[i, <span class="dv">1</span>, <span class="dv">4</span>])</span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># here all participant fixed and random modality effect estimates are combined in a single dataframe</span></span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>  temp_df <span class="ot">&lt;-</span> <span class="fu">rbind</span>(temp_df, participant_df)</span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># reshape from wide to long</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>modality_df <span class="ot">&lt;-</span> temp_df <span class="sc">%&gt;%</span> <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">c</span>(<span class="st">'empirical_olfactory_rt'</span>, <span class="st">'estimated_olfactory_rt'</span>, <span class="st">'empicial_visual_rt'</span>, <span class="st">'estimated_visual_rt'</span>),</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">names_to =</span> <span class="st">'coefficient'</span>,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">values_to =</span> <span class="st">'rt'</span>)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="co"># create new column</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>modality_df<span class="sc">$</span>group <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(modality_df<span class="sc">$</span>coefficient <span class="sc">==</span> <span class="st">"empirical_olfactory_rt"</span>, <span class="st">"empirical"</span>,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>                            <span class="fu">ifelse</span>(modality_df<span class="sc">$</span>coefficient <span class="sc">==</span> <span class="st">"empicial_visual_rt"</span>, <span class="st">"empirical"</span>, <span class="st">"estimated"</span>)))</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="co"># create new column</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>modality_df<span class="sc">$</span>group2 <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(modality_df<span class="sc">$</span>coefficient <span class="sc">==</span> <span class="st">"empirical_olfactory_rt"</span>, <span class="st">"olfactory"</span>,</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>                            <span class="fu">ifelse</span>(modality_df<span class="sc">$</span>coefficient <span class="sc">==</span> <span class="st">"estimated_olfactory_rt"</span>, <span class="st">"olfactory"</span>, <span class="st">"visual"</span>)))</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a><span class="co"># rename columns</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(modality_df) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"participant"</span>, <span class="st">"coefficient"</span>, <span class="st">"rt"</span>, <span class="st">"estimate"</span>, <span class="st">"modality"</span>)</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>modality_df_estimates <span class="ot">&lt;-</span> modality_df[modality_df<span class="sc">$</span>estimate <span class="sc">==</span> <span class="st">"estimated"</span>, ]</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>modality_df_estimates <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(modality_df<span class="sc">$</span>rt, <span class="fu">list</span>(modality_df<span class="sc">$</span>participant, modality_df<span class="sc">$</span>modality), mean)</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(modality_df_estimates) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"participant"</span>, <span class="st">"modality"</span>, <span class="st">"rt"</span>)</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean rt for each modality</span></span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>mean_values <span class="ot">&lt;-</span> modality_df_estimates <span class="sc">%&gt;%</span></span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(modality) <span class="sc">%&gt;%</span></span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_rt =</span> <span class="fu">mean</span>(rt))</span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a>mean_values <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="st">"participant"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">101</span>, <span class="dv">101</span>),</span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"modality"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"olfactory"</span>, <span class="st">"visual"</span>),</span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"rt"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">1837</span>, <span class="dv">612</span>))</span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a>mean_values<span class="sc">$</span>participant <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(mean_values<span class="sc">$</span>participant)</span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a>mean_values<span class="sc">$</span>modality <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(mean_values<span class="sc">$</span>modality)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># graph random effects for modality</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(modality_df_estimates, <span class="fu">aes</span>(<span class="at">x =</span> modality, <span class="at">y =</span> rt, <span class="at">group =</span> participant)) <span class="sc">+</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"grey"</span>) <span class="sc">+</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"grey"</span>)  <span class="sc">+</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> mean_values, <span class="fu">aes</span>(<span class="at">x =</span> modality, <span class="at">y =</span> rt), <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> mean_values, <span class="fu">aes</span>(<span class="at">x =</span> modality, <span class="at">y =</span> rt, <span class="at">group =</span> <span class="dv">1</span>), <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Modality Random Effects"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="1-jneuro-behavioural_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>An alternate way to view this is to put each participants’ random effect estimate on a plot with the fixed effect estimate, and plot each of these on individual panels. Maybe not as intuitive as the previous plot, but it still makes sense to look at it like this.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># empty list where each runner's graph will be saved.</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>temp_list <span class="ot">&lt;-</span> <span class="fu">list</span>()  </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co"># loop through runners, grab their specific intercepts/slope from previous dataframe, and save graph to list</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">unique</span>(modality_df<span class="sc">$</span>participant)) {</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># runner-specific graph</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  temp_graph <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(modality_df[modality_df<span class="sc">$</span>participant <span class="sc">==</span> i, ], <span class="fu">aes</span>(<span class="at">x =</span> modality, <span class="at">y =</span> rt, <span class="at">color =</span> estimate, <span class="at">group =</span> estimate)) <span class="sc">+</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="dv">2800</span>) <span class="sc">+</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="fu">paste0</span>(<span class="st">"Subject "</span>, i)) <span class="sc">+</span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># save ith runner graph to temp_list</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>  temp_list[[i]] <span class="ot">&lt;-</span> temp_graph</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>arg_list <span class="ot">&lt;-</span> <span class="fu">c</span>(temp_list, <span class="fu">list</span>(<span class="at">nrow =</span> <span class="dv">13</span>, <span class="at">ncol =</span> <span class="dv">5</span>))</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Use do.call to pass all elements of graph_list to ggarrange</span></span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>arranged_plots <span class="ot">&lt;-</span> <span class="fu">do.call</span>(<span class="st">"ggarrange"</span>, arg_list)</span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Print or display the arranged plots</span></span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(arranged_plots)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="1-jneuro-behavioural_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>The Bayesian random effects model seems to converge with the frequentist analysis I published. The interpretations, like with the 2-way factorial design, lead to similar conclusions regardless of whether I use p-values or posterior estimates.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/www\.stephenpierzchajlo\.com\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2024 - Stephen Pierzchajlo</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/">
      <i class="bi bi-twitter" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="../../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>